### ISSUE TITLE
你好,可以加你QQ聊一下吗

### ISSUE THREAD

**Issue by IOXusu** [cheikh-wang/LazyWaimai-Api#1]
因为我是做Android开发的,对PhP不是很熟悉,昨天没跑起来安装了PhP环境,,放在Apache里,但是还是没跑起来.我看了你的android代码,我用的MVC结构的开发的,虽然对MVP结构不是很熟悉,但是看你写的很清晰.

**Comment by cheikh-wang** [comment]
LazyWaimai-Android里的api 服务器不是可用吗

**Comment by IOXusu** [comment]
白天是的可用的,我看你开放了后台,想了解一下这个流程.我在windows电脑上运行这个后台遇到了一些问题.
Apache指向了这个项目,但是报错说index.php中  require(__DIR__ . '/../vendor/autoload.php'); 这一行报错,应该缺少一些目录.我在执行compose install 是不行的.

**Comment by cheikh-wang** [comment]
你在终端输入如下命令检查composer是否安装成功
```
composer -V
```
如不能显示如下类似内容：
```
Composer version 1.3.2 2017-01-27 18:23:41
```
你需要先正确安装[composer](https://pkg.phpcomposer.com/)

之后再cd到工程更目录下执行``` composer install```命令。

**Comment by IOXusu** [comment]
这个不知道什么原因,我昨天安装死活装不上去,今天composer安装成功了.现在运行起来了.我还需要看下你的这个后台逻辑.
