### ISSUE TITLE
我部署完服务端报这些错误怎么办？

### ISSUE THREAD

**Issue by styz1** [cheikh-wang/LazyWaimai-Api#5]
An Error occurred while handling another error:
exception 'yii\base\InvalidParamException' with message 'The file or directory to be published does not exist: C:\wamp\www\LazyWaimai-Api-master\vendor\bower/jquery/dist' in C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\web\AssetManager.php:452
Stack trace:
#0 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\web\AssetBundle.php(183): yii\web\AssetManager->publish('C:\\wamp\\www\\Laz...', Array)
#1 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\web\AssetManager.php(266): yii\web\AssetBundle->publish(Object(yii\web\AssetManager))
#2 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\web\AssetManager.php(237): yii\web\AssetManager->loadBundle('yii\\web\\JqueryA...', Array, true)
#3 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\web\View.php(284): yii\web\AssetManager->getBundle('yii\\web\\JqueryA...')
#4 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\web\View.php(289): yii\web\View->registerAssetBundle('yii\\web\\JqueryA...', NULL)
#5 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\web\View.php(289): yii\web\View->registerAssetBundle('yii\\web\\YiiAsse...', NULL)
#6 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\web\AssetBundle.php(123): yii\web\View->registerAssetBundle('app\\assets\\AppA...')
#7 C:\wamp\www\LazyWaimai-Api-master\views\layouts\main.php(11): yii\web\AssetBundle::register(Object(yii\web\View))
#8 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\base\View.php(325): require('C:\\wamp\\www\\Laz...')
#9 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('C:\\wamp\\www\\Laz...', Array)
#10 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\base\Controller.php(393): yii\base\View->renderFile('C:\\wamp\\www\\Laz...', Array, Object(app\controllers\SiteController))
#11 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\base\Controller.php(379): yii\base\Controller->renderContent('<div class="sit...')
#12 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\web\ErrorAction.php(109): yii\base\Controller->render('error', Array)
#13 [internal function]: yii\web\ErrorAction->run()
#14 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\base\Action.php(92): call_user_func_array(Array, Array)
#15 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\Action->runWithParams(Array)
#16 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller->runAction('error', Array)
#17 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\web\ErrorHandler.php(93): yii\base\Module->runAction('site/error')
#18 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\base\ErrorHandler.php(109): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#19 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#20 {main}
Previous exception:
exception 'yii\web\NotFoundHttpException' with message 'Page not found.' in C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\web\Request.php:189
Stack trace:
#0 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\web\Application.php(78): yii\web\Request->resolve()
#1 C:\wamp\www\LazyWaimai-Api-master\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 C:\wamp\www\LazyWaimai-Api-master\web\index.php(12): yii\base\Application->run()
#3 {main}

**Comment by joe-leong** [comment]
老哥，你这个是用wampserver当服务器？

**Comment by cheikh-wang** [comment]
自己单独搭建的，wamp也可以




| |
王宏
邮箱：wanghonghi@126.com
|

签名由 网易邮箱大师 定制

在2018年05月27日 21:30，joe-leong 写道：

老哥，你这个是用wampserver当服务器？

**Comment by cheikh-wang** [comment]
composer global require "fxp/composer-asset-plugin:^1.3.1"
