### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by joe-leong** [cheikh-wang/LazyWaimai-Api#6]
大佬啊，你那个服务器是怎样搭建的，能教一下我吗？

**Comment by cheikh-wang** [comment]
我后面写个详细的文档出来




| |
王宏
邮箱：wanghonghi@126.com
|

签名由 网易邮箱大师 定制

在2018年05月27日 21:26，joe-leong 写道：

大佬啊，你那个服务器是怎样搭建的，能教一下我吗？

**Comment by cheikh-wang** [comment]
是否没有执行此命令 composer global require "fxp/composer-asset-plugin:^1.3.1"
